### ISSUE TITLE
Clicking the logo should redirect back to gridclub.io

### ISSUE THREAD

**Issue by kgourgou** [gridclub/gridclub.github.io#3]
As it is right now, it goes to a 404 page.

**Comment by AruniRC** [comment]
resolved in [commit](https://github.com/gridclub/gridclub.github.io/commit/8f0b480cc7807800b9873f13bc7eb67402a99778)

**Comment by kgourgou** [comment]
Thanks, that was a silly bug. :stuck_out_tongue:
